language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - "10"
  - "11"

before_install:
  # Install latest Yarn.
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn ci

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn codecov
    on:
      tags: false
      node_js: "10"
      branch: master
      repo: umidbekkarimov/memo

  - provider: npm
    skip_cleanup: true
    email: uma.karimov@gmail.com
    api_key:
      secure: $NPM_TOKEN
    on:
      tags: true
      node_js: "10"
      branch: master
      repo: umidbekkarimov/memo
