version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

commands:
  install:
    steps:
      - restore_cache:
          keys:
            - yarn-{{ checksum "package.json" }}
            - yarn-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-{{ checksum "package.json" }}

jobs:
  main:
    executor: node
    parameters:
      publish:
        type: boolean
        default: false
    steps:
      - checkout
      - install
      - run:
          name: Lint
          command: |
            yarn tsc
            yarn lint
      - run:
          name: Test
          command: |
            yarn test
            yarn codecov
      - run:
          name: Build
          command: yarn build
      - when:
          condition: << parameters.publish >>
          steps:
            - run:
                name: Publish to NPM
                command: |
                  echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
                  npm publish pkg

workflows:
  version: 2
  build:
    jobs:
      - main:
          name: build
          filters:
            tags:
              ignore: /.*/

      - main:
          name: publish
          publish: true
          context: npm-pkg
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  scheduled:
    jobs:
      - main
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
