name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - run: npm ci
      - run: npx tsc
      - run: npm run lint
      - run: npm run test
      - uses: codecov/codecov-action@v2.1.0
