name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2
        with:
          node-version: "14"

      - run: npx tsc
      - run: npm run lint
      - run: npm run test
      - uses: codecov/codecov-action@v2.1.0
